services:
  db:
    image: postgres:16
    container_name: fitness-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fitness_prod
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: fitness
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: