spring:
  application:
    name: fitness-tracker
  profiles:
    active: dev

---
spring:
  config:
    activate.on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false

---
spring:
  config:
    activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/fitness_prod
    username: fitness
    password: fitness
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.dialect]': org.hibernate.dialect.PostgreSQLDialect
